name: Release Package Version
on:
  push:
    tags:
     - v*     

env:
  PROJECT_NAME: Cosmology
  SLN_NAME: Cosmology

jobs: 
  build:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:    
    
    - name: Print Tag Ref
      run: echo $GITHUB_REF
      
    - name: Extract Version Number
      uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ github.ref }}
        regex: '([pre0-9.-]+)$'
       
    - name: Print Version Number
      run: echo '${{ steps.regex-match.outputs.match }}'
      
    - uses: actions/checkout@v2
    - name: Setup .NET  
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
        
    - name: Restore dependencies
      run: dotnet restore ./$SLN_NAME.sln
      
    - name: Build
      run: dotnet build ./$PROJECT_NAME.sln
          
    - name: Test
      run: dotnet test ./$PROJECT_NAME.sln
      
    - name: Pack
      run: dotnet pack ./src/$PROJECT_NAME/$PROJECT_NAME.csproj -p:PackageVersion='${{ steps.regex-match.outputs.match }}' --output packages
      
    - name: Publish Package
      run: nuget push **\*.nupkg -NoSymbols -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
      
    - name: Upload Package
      uses: actions/upload-artifact@v2
      with:
        name: $PROJECT_NAME-v${{ steps.regex-match.outputs.match }}
        path: packages/
